language: csharp
solution: cloudscribe.Logging.sln
sudo: false
dist: xenial
mono: none
dotnet: 6.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
  
script:
  - dotnet restore
  - dotnet build -c Release
